
GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"I know Elohim has my best Interest",
    "important":true,
    "id":"id"
}
###
DELETE http://localhost:3001/api/notes/4